import { pirata } from "../public/fonts";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pirata} font-rambla`}
      >
        {children}
      </body>
    </html>
  );
}
